//
//  AudioUnit+Helpers.swift
//  HOWL
//
//  Created by Daniel Clelland on 25/06/16.
//  Copyright © 2016 Daniel Clelland. All rights reserved.
//

import Foundation
import CoreAudio

// MARK: - AudioUnit helpers

extension AudioUnit {
    
    /// Gets a value for a given property. Automatic casting; will crash for invalid properties.
    public func getValue<T>(for property: AudioUnitPropertyID) -> T {
        let (dataSize, _) = try! getPropertyInfo(property)
        return try! getProperty(property, dataSize: dataSize)
    }
    
    /// Sets a value for a given property. Automatic casting; will crash for invalid properties.
    public func setValue<T>(_ value: T, for property: AudioUnitPropertyID) {
        let (dataSize, _) = try! getPropertyInfo(property)
        return try! setProperty(property, dataSize: dataSize, data: value)
    }
}

// MARK: - AudioUnit listeners

extension AudioUnit {
    
    /// Adds a listener block for a property that changes.
    public func add(listener: AudioUnitPropertyListener, to property: AudioUnitPropertyID) {
        try! addPropertyListener(listener, toProperty: property)
    }
    
    /// Removes a listener block for a property that changes.
    public func remove(listener: AudioUnitPropertyListener, from property: AudioUnitPropertyID) {
        try! removePropertyListener(listener, fromProperty: property)
    }
    
}

// MARK: - AudioUnit callbacks

/// A structure that contains the autogenerated Proc and pointer for adding/removing to an AudioUnit.
public struct AudioUnitPropertyListener {
    
    /// A callback block, executed when an audio unit property changes.
    public typealias Callback = (_ audioUnit: AudioUnit, _ property: AudioUnitPropertyID) -> Void
    
    fileprivate let proc: AudioUnitPropertyListenerProc
    fileprivate let procInput: UnsafeMutablePointer<Callback>
    
    /// Initialise a property listener with a callback block.
    public init(_ callback: @escaping Callback) {
        self.proc = { (inRefCon, inUnit, inID, inScope, inElement) in
            inRefCon.assumingMemoryBound(to: Callback.self).pointee(inUnit, inID)
        }
        
        self.procInput = UnsafeMutablePointer<Callback>.allocate(capacity: MemoryLayout<Callback>.stride)
        self.procInput.initialize(to: callback)
    }
    
}

// MARK: - Four character codes

extension UInt32 {
    
    /// Create a `UInt32` with a four character code. Will crash if the string is not four characters long.
    public init(fourCharacterCode: String) {
        assert(fourCharacterCode.characters.count == 4, "String should be four characters long")
        
        let reversed = String(fourCharacterCode.characters.reversed())
        let bytes = (reversed as NSString).utf8String
        let pointer = UnsafeRawPointer(bytes)!.assumingMemoryBound(to: UInt32.self)
        
        self = pointer.pointee.littleEndian
    }
    
    /// Converts the four character code back to a string.
    public var fourCharacterCode: String {
        var bytes = bigEndian
        return String(bytesNoCopy: &bytes, length: 4, encoding: .ascii, freeWhenDone: false)!
    }
    
}

// MARK: - AudioUnit function wrappers

private extension AudioUnit {
    
    func getPropertyInfo(_ propertyID: AudioUnitPropertyID) throws -> (dataSize: UInt32, writable: Bool) {
        var dataSize: UInt32 = 0
        var writable: DarwinBoolean = false
        
        try AudioUnitGetPropertyInfo(self, propertyID, kAudioUnitScope_Global, 0, &dataSize, &writable).check()
        
        return (dataSize: dataSize, writable: writable.boolValue)
    }
    
    func getProperty<T>(_ propertyID: AudioUnitPropertyID, dataSize: UInt32) throws -> T {
        var dataSize = dataSize
        var data = UnsafeMutablePointer<T>.allocate(capacity: Int(dataSize))
        defer {
            data.deallocate(capacity: Int(dataSize))
        }
        
        try AudioUnitGetProperty(self, propertyID, kAudioUnitScope_Global, 0, data, &dataSize).check()
        
        return data.pointee
    }
    
    func setProperty<T>(_ propertyID: AudioUnitPropertyID, dataSize: UInt32, data: T) throws {
        var data = data
        
        try AudioFileSetProperty(self, propertyID, dataSize, &data).check()
    }
    
    func addPropertyListener(_ listener: AudioUnitPropertyListener, toProperty propertyID: AudioUnitPropertyID) throws {
        try AudioUnitAddPropertyListener(self, propertyID, listener.proc, listener.procInput).check()
    }
    
    func removePropertyListener(_ listener: AudioUnitPropertyListener, fromProperty propertyID: AudioUnitPropertyID) throws {
        try AudioUnitRemovePropertyListenerWithUserData(self, propertyID, listener.proc, listener.procInput).check()
    }
    
}

// MARK: - AudioUnit function validation

private extension OSStatus {
    
    func check() throws {
        if self != noErr {
            throw NSError(domain: NSOSStatusErrorDomain, code: Int(self), userInfo: nil)
        }
    }
    
}
